server:
  port: 8091

spring:
  application:
    name: ms-calendar
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/calendarDb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: http://localhost:8181/realms/microservices-realm/protocol/openid-connect/certs
  kafka:
    bootstrapServers: localhost:9092
    #consumer:
      #groupId: scouter-management
      #keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      #valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

