server:
  port: 8761

spring:
  application:
    name: ms-eureka
  ##security:
    ##user:
      ##name: eureka
      ##password: password

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/

##logging:
  ##level:
    ##org:
      ##springframework:
        ##web: debug
        ##security: debug
