eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ms-gateway
  security.oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: http://localhost:8181/realms/spring-microservices-realm/protocol/openid-connect/certs
    client:
      provider:
        keycloak:
          issuer-uri: http://localhost:8181/realms/spring-microservices-realm
      registration:
        spring-with-test-scope:
          provider: keycloak
          client-id: scouting-client-id
          client-secret: YC9sJGAhUE9vKOXb1Y1vKgtd1GnoljPj
          authorization-grant-type: authorization_code
          scope: openid
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8093
          predicates:
            - Path=/api/users/**
        - id: teams
          uri: http://localhost:8093
          predicates:
            - Path=/api/teams/**
        - id: calendar
          uri: http://localhost:8091
          predicates:
            - Path=/api/calendar/**
        - id: players
          uri: http://localhost:8090
          predicates:
            - Path=/api/players/**
        - id: stats
          uri: http://localhost:8090
          predicates:
            - Path=/api/stats/**
        - id: clinic-history
          uri: http://localhost:8090
          predicates:
            - Path=/api/clinic_history/**
        - id: teams
          uri: http://localhost:9090
          predicates:
            - Path=/api/teams/**
        - id: recruitment-stats
          uri: http://localhost:8092
          predicates:
            - Path=/api/recruitment_stats/**
      ##default-filters:
        ##- SaveSession
        ##- TokenRelay
  ##security:
    ##oauth2:
      ##client:
        ##provider:
          ##keycloak:
            ##issuerUri: http://localhost:8181/realms/microservices-realm
      ##registration:
        ##keycloak:
          ##provider: keycloak
          ##scope: openid
          ##clientId: microservices_client
          ##clientSecret: dAuywT9ejF1DbXWuUudKRXssQlhmbqKj
          ##authorizationGrantType: authorization_code
          ##redirectUri: {baseUrl}/login/oauth2/code/keycloak
