eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: discovery
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: users
          uri: http://localhost:8093
          predicates:
            - Path=/api/users/**
        - id: roles
          uri: http://localhost:8093
          predicates:
            - Path=/api/roles/**
        - id: calendar
          uri: http://localhost:8091
          predicates:
            - Path=/api/calendar/**
        - id: players
          uri: http://localhost:8090
          predicates:
            - Path=/api/players/**
        - id: stats
          uri: http://localhost:8090
          predicates:
            - Path=/api/stats/**
        - id: clinic-history
          uri: http://localhost:8090
          predicates:
            - Path=/api/clinic_history/**
        - id: teams
          uri: http://localhost:9090
          predicates:
            - Path=/api/teams/**
        - id: recruitment-stats
          uri: http://localhost:8092
          predicates:
            - Path=/api/recruitment_stats/**
      default-filters:
        - SaveSession
        - TokenRelay
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: http://localhost:8181/realms/microservices-realm
      registration:
        keycloak:
          provider: keycloak
          scope: openid
          clientId: microservices_client
          clientSecret: dAuywT9ejF1DbXWuUudKRXssQlhmbqKj
          authorizationGrantType: authorization_code
          redirectUri: {baseUrl}/login/oauth2/code/keycloak
