server:
  port: 8093

spring:
  application:
    name: ms-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userDb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/spring-microservices-realm/protocol/openid-connect/certs
  kafka:
    bootstrapServers: localhost:9092
    #producer:
     # retries: 1
      #keySerializer: org.apache.kafka.common.serialization.StringSerializer
      #valueSerializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  auth:
    converter:
      resource-id: scouting-client-id
      principle-attribute: preferred_username
